# Generated by Django 4.2.7 on 2024-01-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MushroomDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('latin_name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='woodlandsmushrooms/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
