# Generated by Django 4.2.10 on 2024-02-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_mushroomdetail_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="mushroomdetail",
            name="latitude",
            field=models.FloatField(default=30.1704903),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mushroomdetail",
            name="longitude",
            field=models.FloatField(default=-95.5092479),
            preserve_default=False,
        ),
    ]
